In [20]:
import numpy as np

In [21]:
rows = int(input("Enter the number of rows: "))
columns = int(input("Enter the number of columns: "))

print("\nEnter values for Matrix A:")
A = []

for i in range(rows):
    row = list(map(float, input(f"Enter row {i + 1}: ").split()))
    A.append(row)

A = np.array(A)

print("\nEnter values for Matrix B:")
B = []

for i in range(rows):
    row = list(map(float, input(f"Enter row {i + 1}: ").split()))
    B.append(row)

B = np.array(B)

print("\nMatrix A:")
print(A)

print("\nMatrix B:")
print(B)

Enter the number of rows: 2
Enter the number of columns: 2

Enter values for Matrix A:
Enter row 1: 1 2
Enter row 2: 3 4

Enter values for Matrix B:
Enter row 1: 5 6
Enter row 2: 7 8

Matrix A:
[[1. 2.]
 [3. 4.]]

Matrix B:
[[5. 6.]
 [7. 8.]]


In [23]:
print("\n===== MATRIX OPERATIONS TOOL =====")

print("1. Addition")
print("2. Subtraction")
print("3. Matrix Multiplication")
print("4. Element-wise Multiplication")
print("5. Transpose of Matrix A")
print("6. Determinant of Matrix A")
print("7. Inverse of Matrix A")

try:
    choice = int(input("\nEnter your choice (1-7): "))

    if choice == 1:
        print("\nMatrix Addition:")
        print(A + B)

    elif choice == 2:
        print("\nMatrix Subtraction:")
        print(A - B)

    elif choice == 3:
        print("\nMatrix Multiplication:")
        print(np.dot(A, B))

    elif choice == 4:
        print("\nElement-wise Multiplication:")
        print(A * B)

    elif choice == 5:
        print("\nTranspose of Matrix A:")
        print(A.T)

    elif choice == 6:
        if rows == columns:
            print("\nDeterminant of Matrix A:")
            print(np.linalg.det(A))
        else:
            print("\nDeterminant is only possible for a square matrix.")

    elif choice == 7:
        if rows == columns:
            determinant = np.linalg.det(A)

            if np.isclose(determinant, 0):
                print("\nMatrix A does not have an inverse.")
            else:
                print("\nInverse of Matrix A:")
                print(np.linalg.inv(A))
        else:
            print("\nInverse is only possible for a square matrix.")

    else:
        print("\nInvalid choice! Please enter a number between 1 and 7.")

except ValueError:
    print("\nInvalid input! Please enter valid numbers.")


===== MATRIX OPERATIONS TOOL =====
1. Addition
2. Subtraction
3. Matrix Multiplication
4. Element-wise Multiplication
5. Transpose of Matrix A
6. Determinant of Matrix A
7. Inverse of Matrix A

Enter your choice (1-7): 3

Matrix Multiplication:
[[19. 22.]
 [43. 50.]]
